version: '3'

services:
  nginx:
    image: nginx:1.13
    container_name: nginx
    restart: always
    ports:
      - 80:80
    volumes:
      - ./config/nginx/local.conf.d:/etc/nginx/conf.d
      - ./static/static_data:/opt/services/survey/src/back_static
      - ./static/media_data:/opt/services/survey/src/back_media
    depends_on:
      - back
    links:
      - back
    networks:
      - nginx_network