version: '3'

services:
  back:
    container_name: back
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - src/.env
    volumes:
      - .:/opt/services/survey
      - ./static/static_data:/opt/services/survey/src/back_static
      - ./static/media_data:/opt/services/survey/src/back_media
    networks:
      - nginx_network
      - db_network
    depends_on:
      - db
    links:
      - db

  db:
    image: postgres
    container_name: db
    restart: always
    env_file:
      - src/.env
    networks:
      - db_network
    volumes:
      - ./storage/postgres_data:/var/lib/postgresql/data

networks:
  nginx_network:
    driver: bridge
  db_network:
    driver: bridge